### ISSUE TITLE
Hostname is all capitals on Windows

### ISSUE THREAD

**Issue by WilliamVenner** [OxyDeadbeef/whoami#39]
**Describe the bug**
The hostname returned by `whoami::hostname` is in all capitals on Windows.

**To Reproduce**
```toml
[dependencies]
whoami = "1"
hostname = "0.3"
```
```rust
fn main() {
    println!("whoami {:?}", whoami::hostname());
    println!("hostname {:?}", hostname::get());
}
```

**Expected behavior**
The hostname should be returned in the correct casing.

**Screenshots**
![image](https://user-images.githubusercontent.com/14863743/188199633-da065469-d28d-422a-a182-f7c892da43ae.png)

**Comment by WilliamVenner** [comment]
This is on Windows 11 BTW. Not sure about the others

**Comment by AldaronLau** [comment]
@WilliamVenner Thank you for reporting!  I'll look into it.

**Comment by WilliamVenner** [comment]
Notably, `whoami::devicename()` returns the correct casing. Maybe this is the intended behaviour of hostnames on Windows?

**Comment by AldaronLau** [comment]
After looking at it, I believe the current behavior is correct.  The difference between `hostname()` and `devicename()` is that `devicename()` takes into account "fancy" styling which generally ignored by hostnames (such as casing on Windows, and on Linux can also include spaces and punctuation).

It might even make more sense to normalize the hostname returned by the OS to lowercase across all platforms (since Windows is the only one that returns it in all capitals; other platforms return the case-insensitive string in all lowercase).

**Comment by WilliamVenner** [comment]
Ok yeah, that makes sense. Thank you!
